name: Auto-Sync Untappd Menu

on:
  schedule:
    - cron: '34 * * * *' # Run at 34 minutes past every hour
  workflow_dispatch: # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install Dependencies
        run: npm ci

      - name: Fetch and Sync Untappd Menu
        run: npm run sync-untappd

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Check if there are changes in the specific data directory
          if git diff --exit-code src/data/beers.json; then
              echo "No changes to the menu."
              exit 0
          fi
          
          echo "Data changed, committing..."
          git add src/data/beers.json
          git commit -m "Auto-update untappd menu data"
          
          git push
